name: terraform

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: terraform_test'
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        id:   apply
        run: |
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
     
